[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip', 'python3Packages.virtualenv']

[phases.install]
cmds = [
    'cd agent && python -m venv venv && source venv/bin/activate && pip install -r requirements.txt'
]



[start]
cmd = 'cd agent && source venv/bin/activate && uvicorn pdf_api:app --host 0.0.0.0 --port $PORT'