[phases.setup]
nixPkgs = ['nodejs', 'python3', 'python3Packages.pip']

[phases.install]
cmds = [
    'cd web && npm install',
    'cd agent && pip install -r requirements.txt'
]

[phases.build]
cmds = ['cd web && npm run build']

[start]
cmd = 'cd web && npm start & cd agent && python pdf_api.py & python main.py dev'