[phases.setup]
nixPkgs = ['nodejs']

[phases.install]
cmds = [
    'cd web && npm install -g pnpm && pnpm install'
]

[phases.build]
cmds = ['cd web && pnpm build']

[start]
cmd = 'cd web && pnpm start'