[phases.setup]
nixPkgs = ['nodejs', 'python3', 'python3Packages.pip']

[phases.install]
cmds = [
    'cd web && npm install',
    'cd agent && pip install -r requirements.txt'
]

[phases.build]
cmds = ['cd web && npm run build']

[start]
cmd = 'cd agent && uvicorn pdf_api:app --host 0.0.0.0 --port $PORT'